import { Panel } from '../components/Shell'
import stats from '../data/model_stats.json'

/**
 * Model performance.
 *
 * These figures were previously pinned to the sidebar, visible on every screen
 * including while an analyst was reading a single case. They describe how the
 * detection system behaves across a held-out test set — they say nothing about
 * the case on screen, and sitting beside one invited exactly that reading.
 *
 * Everything here is generated from data/metrics.json, which only the training
 * and evaluation scripts write. Nothing on this page is typed by hand.
 */

const pct = (v, dp = 1) => `${(v * 100).toFixed(dp)}%`

function Figure({ label, value, sub, tone = 'default' }) {
  const tones = { default: 'text-zinc-100', good: 'text-aegis-green', warn: 'text-amber-400' }
  return (
    <div className="rounded border border-ink-border bg-ink-bg px-3 py-2.5">
      <div className="text-[11px] text-zinc-500">{label}</div>
      <div className={`mono tnum text-[17px] font-semibold mt-0.5 ${tones[tone]}`}>{value}</div>
      {sub && <div className="text-[11px] text-zinc-500 mt-0.5">{sub}</div>}
    </div>
  )
}

export default function ModelPerformance() {
  const { truePositives: tp, falsePositives: fp, falseNegatives: fn, trueNegatives: tn } = stats
  const measured = new Date(stats.measuredUtc).toLocaleString('en-IN', {
    day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit',
  })

  return (
    <div className="p-4 space-y-4 max-w-[1400px]">
      <div>
        <h1 className="text-[15px] font-semibold text-white">Model performance</h1>
        <p className="text-[12.5px] text-zinc-400 mt-1 max-w-3xl leading-relaxed">
          How the detection and location models score against held-out data they
          were never trained on. These describe the system as a whole. They are
          not a confidence level for any individual case, and should not be read
          as one.
        </p>
        <p className="text-[11px] text-zinc-500 mt-1.5">
          Last evaluated {measured} · generated by{' '}
          <span className="mono">scripts/export_metrics.py</span>
        </p>
      </div>

      {/* ── Mule detection ─────────────────────────────────────────────── */}
      <Panel title="Mule account detection" right="GraphSAGE">
        <div className="p-3 space-y-3">
          <div className="grid grid-cols-2 lg:grid-cols-5 gap-2">
            <Figure label="F1" value={stats.gnnF1.toFixed(4)} tone="good"
                    sub={`vs ${stats.gnnBaseline.toFixed(4)} best non-graph`} />
            <Figure label="Precision" value={pct(stats.precision, 2)} sub="of flagged, correct" />
            <Figure label="Recall" value={pct(stats.recall, 2)} sub="of mules, found" />
            <Figure label="ROC-AUC" value={stats.rocAuc.toFixed(4)} />
            <Figure label="PR-AUC" value={stats.prAuc.toFixed(4)} sub="the honest one when rare" />
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-3">
            {/* Confusion matrix — counted from the frozen test split by
                scripts/export_confusion.py, not reconstructed from rounded
                precision and recall. */}
            <div>
              <div className="text-[11px] text-zinc-400 mb-1.5">
                Confusion matrix · {stats.nTestAccounts.toLocaleString('en-IN')} held-out accounts,
                {' '}{stats.actualMules} of them mules
              </div>
              <table className="w-full text-[12px] border border-ink-border rounded overflow-hidden">
                <thead>
                  <tr className="bg-ink-panel/60 text-zinc-500">
                    <th className="px-3 py-1.5 text-left font-medium" />
                    <th className="px-3 py-1.5 text-right font-medium">Flagged</th>
                    <th className="px-3 py-1.5 text-right font-medium">Not flagged</th>
                  </tr>
                </thead>
                <tbody className="mono tnum">
                  <tr className="border-t border-ink-border">
                    <td className="px-3 py-1.5 text-zinc-400">Actually a mule</td>
                    <td className="px-3 py-1.5 text-right text-aegis-green">{tp}</td>
                    <td className="px-3 py-1.5 text-right text-amber-400">{fn}</td>
                  </tr>
                  <tr className="border-t border-ink-border">
                    <td className="px-3 py-1.5 text-zinc-400">Actually clean</td>
                    <td className="px-3 py-1.5 text-right text-amber-400">{fp}</td>
                    <td className="px-3 py-1.5 text-right text-zinc-300">{tn.toLocaleString('en-IN')}</td>
                  </tr>
                </tbody>
              </table>
              <p className="text-[11.5px] text-zinc-400 mt-2 leading-relaxed">
                In an alert queue this reads as: of <b className="text-zinc-200">{tp + fp}</b>{' '}
                accounts flagged, <b className="text-zinc-200">{tp}</b> are mules — an analyst
                opens roughly {(fp / Math.max(1, tp + fp) * 100).toFixed(0)} false
                positives in every hundred. <b className="text-zinc-200">{fn}</b> mules are
                missed at the operating threshold of{' '}
                <span className="mono">{stats.threshold.toFixed(4)}</span>.
              </p>
            </div>

            <div>
              <div className="text-[11px] text-zinc-400 mb-1.5">
                Against models with no access to the transaction graph
              </div>
              <div className="space-y-1.5">
                {Object.entries(stats.detectionBaselines).map(([name, f1]) => (
                  <div key={name} className="flex items-center gap-2">
                    <span className="text-[11.5px] text-zinc-400 w-[190px] shrink-0 truncate" title={name}>
                      {name}
                    </span>
                    <div className="flex-1 h-2 bg-ink-bg border border-ink-border rounded overflow-hidden">
                      <span className="block h-full bg-zinc-600" style={{ width: `${f1 * 100}%` }} />
                    </div>
                    <span className="mono tnum text-[11.5px] text-zinc-400 w-12 text-right">
                      {f1.toFixed(3)}
                    </span>
                  </div>
                ))}
                <div className="flex items-center gap-2 pt-1">
                  <span className="text-[11.5px] text-zinc-200 w-[190px] shrink-0 font-medium">
                    GraphSAGE (this system)
                  </span>
                  <div className="flex-1 h-2 bg-ink-bg border border-ink-border rounded overflow-hidden">
                    <span className="block h-full bg-aegis-green"
                          style={{ width: `${stats.gnnF1 * 100}%` }} />
                  </div>
                  <span className="mono tnum text-[11.5px] text-aegis-green w-12 text-right font-semibold">
                    {stats.gnnF1.toFixed(3)}
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </Panel>

      {/* ── Cash-out location ──────────────────────────────────────────── */}
      <Panel title="Cash-out location" right="Ranked retrieval">
        <div className="p-3 space-y-3">
          <p className="text-[12.5px] text-zinc-400 leading-relaxed max-w-3xl">
            The system does not name the ATM a suspect will use. It returns the{' '}
            {stats.operatingK} locations worth searching first, ordered. Containment
            is how often the actual cash-out was among them, over{' '}
            {stats.nTestCashouts} held-out cases.
          </p>

          <div className="overflow-x-auto">
            <table className="data-table max-w-2xl">
              <thead>
                <tr>
                  <th>Locations searched</th>
                  <th className="text-right">Containment</th>
                  <th className="text-right">Distance-only</th>
                  <th className="text-right">Search reduced by</th>
                </tr>
              </thead>
              <tbody>
                {stats.rankingCurve.map(r => (
                  <tr key={r.K} aria-selected={r.K === stats.operatingK}>
                    <td className={r.K === stats.operatingK ? 'text-white font-medium' : ''}>
                      Top {r.K}{r.K === stats.operatingK && ' · in use'}
                    </td>
                    <td className="text-right mono tnum">{pct(r.containment)}</td>
                    <td className="text-right mono tnum text-zinc-500">{pct(r.baseline)}</td>
                    <td className="text-right mono tnum text-zinc-500">{pct(r.reduction, 2)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Stated here because it is the first thing a reviewer checks, and
              burying it would be the kind of omission that discredits the rest. */}
          <p className="text-[12px] text-amber-400/90 leading-relaxed max-w-3xl border-l-2 border-amber-500/40 pl-3">
            At the operating point the ranker does not beat sorting by distance
            ({pct(stats.top5Containment)} against {pct(stats.top5BaselineDistance)}),
            and the difference is not statistically significant at any K. The
            defensible claim is the narrowing — {stats.atmTotal.toLocaleString("en-IN")} ATMs to{" "}
            {stats.operatingK} — not that the model outperforms a distance rule.
          </p>

          <div className="grid grid-cols-2 lg:grid-cols-4 gap-2">
            <Figure label="Search zone containment" value={pct(stats.zoneContainment)}
                    sub={`vs ${pct(stats.zoneBaselineNearest3)} nearest-3`} tone="good" />
            <Figure label="Median location error" value={`${stats.zoneMedianErrorKm.toFixed(2)} km`} />
            <Figure label="Time-to-cash-out error" value={`${stats.countdownMae.toFixed(1)} min`}
                    sub={`vs ${stats.countdownBaseline.toFixed(1)} min baseline · R² ${stats.countdownR2.toFixed(2)}`} />
            <Figure label="Median warning time" value={`${stats.leadTimeMedianMin.toFixed(0)} min`}
                    sub={`inference ${stats.inferenceMeanMs.toFixed(1)} ms`} />
          </div>
        </div>
      </Panel>
    </div>
  )
}
