# -*- coding: utf-8 -*-
"""
Build the four analysis notebooks under notebooks/.

    python scripts/build_notebooks.py

The notebooks are GENERATED, not hand-edited, so they cannot drift away from the
engine they document. Every one of them:

  * imports the real modules from engine/ rather than reimplementing anything,
  * evaluates the SHIPPED checkpoints instead of retraining (the one exception is
    the conditional logit, which fits in well under a second and is deterministic),
  * and cross-checks each figure it computes against data/metrics.json, printing
    MATCH or MISMATCH.

That last property is the point. A notebook whose numbers disagree with the
README is worse than no notebook, so the comparison is executed rather than
asserted in prose.
"""

import json
from pathlib import Path

import nbformat as nbf

ROOT = Path(__file__).parent.parent
OUT = ROOT / "notebooks"
OUT.mkdir(exist_ok=True)


def md(text: str) -> nbf.NotebookNode:
    return nbf.v4.new_markdown_cell(text.strip("\n"))


def code(text: str) -> nbf.NotebookNode:
    return nbf.v4.new_code_cell(text.strip("\n"))


def write(name: str, title: str, cells: list) -> None:
    nb = nbf.v4.new_notebook()
    nb.cells = cells
    nb.metadata = {
        "kernelspec": {"display_name": "Python 3", "language": "python",
                       "name": "python3"},
        "language_info": {"name": "python"},
    }
    path = OUT / name
    nbf.write(nb, str(path))
    print(f"  {path.relative_to(ROOT)}  ({len(cells)} cells)  {title}")


# The preamble every notebook opens with: find the project root from wherever the
# kernel was started, put engine/ on the path, and load the published metrics.
PREAMBLE = '''
import sys, json, warnings
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

warnings.filterwarnings("ignore")
pd.set_option("display.width", 120)
plt.rcParams.update({"figure.dpi": 110, "font.size": 9, "axes.grid": True,
                     "grid.alpha": 0.25, "axes.spines.top": False,
                     "axes.spines.right": False})

# Works whether the kernel starts in notebooks/ or at the project root.
ROOT = Path.cwd()
while not (ROOT / "engine").is_dir() and ROOT != ROOT.parent:
    ROOT = ROOT.parent
sys.path.insert(0, str(ROOT / "engine"))

DATA = ROOT / "data"
MODELS = ROOT / "models"

# The published numbers. Everything below is checked against this file.
METRICS = json.loads((DATA / "metrics.json").read_text())

def check(label, got, expected, tol=5e-3):
    """Print whether a freshly computed figure matches the published one."""
    ok = abs(float(got) - float(expected)) <= tol
    print(f"  {'MATCH   ' if ok else 'MISMATCH'}  {label:38s} "
          f"notebook={float(got):.4f}  published={float(expected):.4f}")
    return ok

print("project root :", ROOT)
print("metrics from :", METRICS["_about"][:60], "...")
'''


# ───────────────────────────────────────────────────────────────────────────────
# 01 — EDA
# ───────────────────────────────────────────────────────────────────────────────

def nb_eda():
    c = []
    c.append(md("""
# 01 · Exploratory Data Analysis

**MuleShield AI — SIH26184 (MHA / I4C)**

What the corpus contains, how the laundering chains are shaped, and — most
importantly — a check that no single feature gives the label away.

The dataset is **synthetic**. Real NCRP transaction data is legally restricted,
so the ledger is generated by `scripts/generate_data.py` from documented
laundering typology (layering, fund-splitting, many-to-one pooling). What that
means for the claims in this project is spelled out at the end of the notebook.
"""))
    c.append(code(PREAMBLE))

    c.append(md("## 1 · What is in the corpus"))
    c.append(code('''
txn   = pd.read_csv(DATA / "transactions.csv", low_memory=False)
node  = pd.read_csv(DATA / "node_features.csv")
comp  = pd.read_csv(DATA / "victim_complaints.csv")
atm   = pd.read_csv(DATA / "atm_directory.csv")

print(f"transactions   {len(txn):>8,}")
print(f"accounts       {len(node):>8,}")
print(f"complaints     {len(comp):>8,}")
print(f"ATMs           {len(atm):>8,}")
print()
print(f"fraud txns     {int((txn.is_fraud == 1).sum()):>8,}")
print(f"terminal txns  {int((txn.is_terminal == 1).sum()):>8,}   <- cash-out events")
print(f"labelled mules {int(node.is_mule_label.sum()):>8,}   "
      f"({100 * node.is_mule_label.mean():.2f}% prevalence)")
'''))

    c.append(md("""
Prevalence of ~3% matters more than it looks. It is why F1 at a 0.5 threshold is
a poor summary and why the detector ships with a tuned threshold — a point the
detection notebook returns to.
"""))

    c.append(md("## 2 · Shape of a laundering chain"))
    c.append(code('''
fraud = txn[txn.is_fraud == 1]

hop = fraud.groupby("hop_depth").agg(
    transfers=("txn_id", "count"),
    median_amount=("amount", "median"),
    terminal=("is_terminal", "sum"),
)
display(hop)

fig, ax = plt.subplots(1, 2, figsize=(10, 3))
hop["transfers"].plot(kind="bar", ax=ax[0], color="#3d8b00")
ax[0].set_title("Transfers per hop depth"); ax[0].set_xlabel("hop")

hop["median_amount"].plot(kind="bar", ax=ax[1], color="#c77b30")
ax[1].set_title("Median amount per hop (Rs)"); ax[1].set_xlabel("hop")
plt.tight_layout(); plt.show()
'''))

    c.append(md("""
Amounts fall with depth because each mule keeps a cut (the generator's
`passthrough` trait). Transfers rise then fall as chains fan out and then pool
into shared terminal accounts.
"""))

    c.append(code('''
# Fan-out: how many destinations does one account send to inside a chain?
fan = fraud.groupby(["complaint_id", "src_account"]).size()
print("Fan-out per sending account within a chain")
print(fan.value_counts().sort_index().head(6).to_string())

# Convergence: many-to-one pooling onto a shared terminal
term = fraud[fraud.is_terminal == 1]
conv = term.groupby(["complaint_id", "dst_account"]).size()
print(f"\\nTerminal accounts fed by 3+ sources: "
      f"{int((conv >= 3).sum()):,} of {len(conv):,} "
      f"({100 * (conv >= 3).mean():.1f}%)")
'''))

    c.append(md("## 3 · The cash-out delay is bimodal, on purpose"))
    c.append(code('''
delay = txn.loc[txn.is_terminal == 1, "time_to_cashout_min"].dropna()

fig, ax = plt.subplots(figsize=(8, 3))
ax.hist(delay, bins=80, color="#3d8b00", alpha=0.85)
ax.axvline(delay.median(), color="#c0392b", ls="--",
           label=f"median {delay.median():.1f} min")
ax.set_xlabel("minutes from final transfer to withdrawal")
ax.set_ylabel("cash-outs"); ax.legend()
ax.set_title("Two regimes: a runner already at the machine, or someone travelling")
plt.tight_layout(); plt.show()

print(delay.describe().round(2).to_string())
'''))

    c.append(md("""
The left mode is a crew with a runner already standing at the ATM; the right mode
is travel time. This was a deliberate modelling decision — a single-regime delay
with a ~22-minute floor never produces an urgent case, which would make any
"did we have time to act?" metric trivially 100% and hide exactly the cases the
system exists to catch.
"""))

    c.append(md("## 4 · Distance decay — the criminology the ranker relies on"))
    c.append(code('''
import math

def hav(lat1, lon1, lat2, lon2):
    r = 6371.0
    p1, p2 = np.radians(lat1), np.radians(lat2)
    dphi, dlam = np.radians(lat2 - lat1), np.radians(lon2 - lon1)
    a = np.sin(dphi / 2) ** 2 + np.cos(p1) * np.cos(p2) * np.sin(dlam / 2) ** 2
    return 2 * r * np.arcsin(np.sqrt(np.clip(a, 0, 1)))

cash = txn[(txn.is_terminal == 1) & txn.cashout_atm_id.notna()].copy()
loc = node.set_index("account_id")[["lat", "long"]]
atm_loc = atm.set_index("atm_id")[["lat", "long"]]

j = cash.join(loc, on="dst_account", rsuffix="_acc").join(atm_loc, on="cashout_atm_id", rsuffix="_atm")
j = j.dropna(subset=["lat", "lat_atm"])
d = hav(j["lat"].values, j["long"].values, j["lat_atm"].values, j["long_atm"].values)

fig, ax = plt.subplots(figsize=(8, 3))
ax.hist(d, bins=60, color="#2f6b8a", alpha=0.85)
ax.axvline(np.median(d), color="#c0392b", ls="--", label=f"median {np.median(d):.2f} km")
ax.set_xlabel("km from terminal account to the ATM actually used")
ax.set_ylabel("cash-outs"); ax.legend()
ax.set_title("Journey to cash-out")
plt.tight_layout(); plt.show()

print(f"median {np.median(d):.2f} km   mean {d.mean():.2f} km   90th pct {np.percentile(d, 90):.2f} km")
'''))

    c.append(md("""
Offence probability falling off with distance from an anchor point is one of the
most robust findings in environmental criminology (Brantingham & Brantingham's
crime pattern theory; the journey-to-crime literature). The generator encodes it
as `exp(-d / 5 km)` and the ranker's first feature is exactly that term.
"""))

    c.append(md("""
## 5 · The leakage check — does any single feature give the label away?

This is the section that matters most for credibility. An earlier build of this
dataset had three construction artefacts that made detection far too easy; the
worst of them let one feature separate the classes at **AUC 0.96 on its own**.
They were found, removed, and the headline F1 was re-measured *downward* from an
invalid 0.9386 to 0.8955.

If any feature below scores near 1.0, the dataset is broken again.
"""))
    c.append(code('''
from sklearn.metrics import roc_auc_score
from gnn_model import FEATURE_COLS, derive_features

nd = derive_features(node)
y = nd["is_mule_label"].to_numpy()

rows = []
for col in FEATURE_COLS:
    v = nd[col].astype(float).to_numpy()
    auc = roc_auc_score(y, v)
    rows.append((col, max(auc, 1 - auc)))   # direction-agnostic

auc_df = (pd.DataFrame(rows, columns=["feature", "standalone_auc"])
            .sort_values("standalone_auc", ascending=False)
            .reset_index(drop=True))
display(auc_df.style.background_gradient(subset=["standalone_auc"], cmap="Oranges"))

worst = auc_df.standalone_auc.max()
top = auc_df.iloc[0]

# The red line is the DOCUMENTED artefact level, not a round number picked here.
# Before the generator was repaired, "this account has almost no ordinary banking
# history" separated the classes at AUC 0.96 on its own (OVERNIGHT_ML_AUDIT.md,
# artefact A1). That is the state this check exists to detect a return to.
ARTEFACT_AUC = 0.96

print(f"strongest single feature : {top.feature} at {worst:.4f} AUC")
print(f"documented artefact level: {ARTEFACT_AUC:.4f} (pre-fix state)")
print("VERDICT:", "OK - below the artefact level" if worst < ARTEFACT_AUC
      else "PROBLEM - the data has regressed to the pre-fix state")
'''))

    c.append(md("""
`txn_count_24h` and `burst_out_5min` sit around **0.90 AUC**, which looks alarming
until you separate two different questions.

**AUC asks "does this feature rank accounts well?"** — and yes, it does, because a
mule genuinely *is* an account that transacts in rapid bursts. That is the real
behavioural phenomenon the detector is supposed to key on, not an artefact.

**F1 asks "can this feature classify accounts on its own?"** — and at 2.95%
prevalence the answer is no. The cell below measures it directly. A feature that
truly gave the label away would score highly on both.
"""))
    c.append(code('''
from sklearn.metrics import f1_score

# Best achievable F1 from a single threshold on the strongest feature.
v = nd[top.feature].astype(float).to_numpy()
best = 0.0
for t in np.percentile(v, np.linspace(1, 99, 200)):
    for sign in (1, -1):
        pred = ((v > t) if sign == 1 else (v <= t)).astype(int)
        if 0 < pred.sum() < len(pred):
            best = max(best, f1_score(y, pred, zero_division=0))

print(f"{top.feature}")
print(f"  ranks well          : AUC {worst:.4f}")
print(f"  classifies poorly   : best single-threshold F1 {best:.4f}")
print(f"  random forest (all 15 features) reaches F1 "
      f"{METRICS['detection_baselines']['best_non_graph']:.4f}")
print(f"  GraphSAGE reaches F1 {METRICS['detection']['test_f1']:.4f}")
print()
print("A single feature that solved the task would push the numbers below it")
print("toward 1.0. It does not, so the signal is real but far from sufficient -")
print("which is exactly the regime a detector should be operating in.")
'''))

    c.append(md("## 6 · Feature correlation"))
    c.append(code('''
corr = nd[FEATURE_COLS].corr().abs()

fig, ax = plt.subplots(figsize=(7.5, 6))
im = ax.imshow(corr, cmap="Blues", vmin=0, vmax=1)
ax.set_xticks(range(len(FEATURE_COLS))); ax.set_xticklabels(FEATURE_COLS, rotation=90)
ax.set_yticks(range(len(FEATURE_COLS))); ax.set_yticklabels(FEATURE_COLS)
plt.colorbar(im, fraction=0.046)
ax.set_title("Absolute feature correlation")
plt.tight_layout(); plt.show()

hi = [(FEATURE_COLS[i], FEATURE_COLS[j], corr.iloc[i, j])
      for i in range(len(FEATURE_COLS)) for j in range(i + 1, len(FEATURE_COLS))
      if corr.iloc[i, j] > 0.9]
print("Pairs above r = 0.90:", hi if hi else "none")
'''))

    c.append(md("""
Near-duplicate columns were already dropped during feature selection
(`in_degree` was r = 1.000 with `txn_count_24h` — literally the same column
twice). `lat`/`long` were dropped as pure noise: mules are spread across all 79
cities, so coordinates carry no signal about whether an account is one.
"""))

    c.append(md("## 7 · Mule vs clean, feature by feature"))
    c.append(code('''
show = ["account_age_days", "burst_out_5min", "passthrough_ratio",
        "median_dwell_seconds", "night_txn_ratio", "activity_per_day"]

fig, axes = plt.subplots(2, 3, figsize=(11, 5))
for ax, col in zip(axes.ravel(), show):
    for lab, colr, name in [(0, "#7f8c8d", "clean"), (1, "#c0392b", "mule")]:
        v = nd.loc[nd.is_mule_label == lab, col].astype(float)
        v = v[np.isfinite(v)]
        if col in ("median_dwell_seconds", "activity_per_day"):
            v = np.log1p(v)
        ax.hist(v, bins=40, alpha=0.55, density=True, color=colr, label=name)
    ax.set_title(col + (" (log1p)" if col in ("median_dwell_seconds", "activity_per_day") else ""),
                 fontsize=8)
    ax.legend(fontsize=7)
plt.tight_layout(); plt.show()
'''))

    c.append(md("""
The distributions **overlap**. That is the intended state — separable classes
would mean the task is trivial and the reported scores meaningless.
"""))

    c.append(md("""
## What this dataset does and does not license us to claim

**Structure is defensible.** Layering, fund-splitting and many-to-one pooling are
documented FATF/RBI laundering typologies. Distance decay is established
criminology. RBI's own MuleHunter.AI is built on 19 enumerated behavioural
patterns, which is itself evidence that such patterns are real and enumerable.

**Parameter values are chosen, not estimated.** The decay length (5 km), the
surveillance-risk weight (2.0), the same-bank boost (2.0) and the crew-preference
boost (9.0) are design constants. Nobody measured that Indian mule crews prefer
own-bank ATMs by a factor of exactly two.

**Therefore:** the synthetic corpus validates the *method*, not the *performance*.
Every score in the notebooks that follow is a real measurement on this generative
process. None of them is a prediction about what the system would score in Delhi.
What transfers to real data is the architecture, the relative comparisons, and the
code — not the absolute numbers.
"""))
    return c


# ───────────────────────────────────────────────────────────────────────────────
# 02 — GraphSAGE detection
# ───────────────────────────────────────────────────────────────────────────────

def nb_gnn():
    c = []
    c.append(md("""
# 02 · GraphSAGE — mule detection

**Model 2 of 3.** Scores every account in a traced chain for mule probability.

Note what this model does **not** do: it does not find the terminal account.
That is deterministic breadth-first search over the transaction graph
(`engine/graph_engine.py`), which means the location forecast downstream does not
depend on this classifier being right.

This notebook evaluates the **shipped checkpoint** on the **split persisted
inside that checkpoint**, so the numbers reproduce the README exactly rather than
re-splitting and drifting.
"""))
    c.append(code(PREAMBLE))

    c.append(md("## 1 · Features, and one deliberate omission"))
    c.append(code('''
from gnn_model import (GraphSAGEMule, FEATURE_COLS, BASE_FEATURE_COLS,
                       DERIVED_FEATURE_COLS, derive_features,
                       IN_CHANNELS, HIDDEN_CHANNELS, OUT_CHANNELS)

print(f"input dim {IN_CHANNELS}  =  {len(BASE_FEATURE_COLS)} measured "
      f"+ {len(DERIVED_FEATURE_COLS)} derived\\n")
for f in BASE_FEATURE_COLS:    print("  measured :", f)
for f in DERIVED_FEATURE_COLS: print("  derived  :", f)
'''))
    c.append(md("""
`hop_depth` is **excluded on purpose.** It records an account's position in an
already-traced fraud chain, so it is non-zero only for accounts we have *already
concluded* are part of one. Feeding it to the classifier would assume the answer.
It stays in `node_features.csv` for the money-flow visualisation only.
"""))

    c.append(md("## 2 · The shipped checkpoint"))
    c.append(code('''
import torch

ckpt = torch.load(MODELS / "graphsage_mule.pt", map_location="cpu", weights_only=False)
print("checkpoint keys:", sorted(ckpt.keys()))

split = ckpt["split"]
print(f"\\ntrain {len(split['train_idx']):>7,}")
print(f"val   {len(split['val_idx']):>7,}")
print(f"test  {len(split['test_idx']):>7,}")
print(f"\\nthreshold shipped: {ckpt.get('threshold', float('nan')):.4f}")

model = GraphSAGEMule(IN_CHANNELS, HIDDEN_CHANNELS, OUT_CHANNELS)
n_params = sum(p.numel() for p in model.parameters())
print(f"parameters       : {n_params:,}")
'''))
    c.append(md("""
About ten thousand parameters. That is small on purpose — it is set by how much
information the data contains, not by ambition. Section 6 shows the model sits at
97% of its measurable ceiling, so capacity is not the binding constraint.
"""))

    c.append(md("## 3 · Reproduce the published test metrics"))
    c.append(code('''
from sklearn.metrics import (f1_score, precision_score, recall_score,
                             roc_auc_score, average_precision_score,
                             accuracy_score, confusion_matrix)

# Rebuild the graph exactly as the trainer did.
# load_pyg_data returns FOUR values (its type annotation says three - the
# annotation is stale, the fourth is the split index dict). We take the split
# from the checkpoint instead, so the fourth is discarded here.
from train_gnn import load_pyg_data
data, account_ids, scaler, _split_idx = load_pyg_data()

model.load_state_dict(ckpt["model_state_dict"])
model.eval()
with torch.no_grad():
    logits = model(data.x, data.edge_index).squeeze()
    prob = torch.sigmoid(logits).numpy()

te = np.array(split["test_idx"])
y_true = data.y.numpy()[te]
y_prob = prob[te]
thr = float(ckpt["hyperparams"]["threshold"])
y_pred = (y_prob >= thr).astype(int)

pub = METRICS["detection"]
print("Reproducing data/metrics.json -> detection\\n")
check("test F1",        f1_score(y_true, y_pred),            pub["test_f1"])
check("test precision", precision_score(y_true, y_pred),     pub["test_precision"])
check("test recall",    recall_score(y_true, y_pred),        pub["test_recall"])
check("test ROC-AUC",   roc_auc_score(y_true, y_prob),       pub["test_auc"])
check("test PR-AUC",    average_precision_score(y_true, y_prob), pub["test_pr_auc"])
check("test accuracy",  accuracy_score(y_true, y_pred),      pub["test_accuracy"])
'''))

    c.append(md("## 4 · Confusion matrix at the operating threshold"))
    c.append(code('''
tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
cm = METRICS["detection_confusion"]

print(f"                 predicted clean   predicted mule")
print(f"actual clean  {tn:>16,} {fp:>16,}")
print(f"actual mule   {fn:>16,} {tp:>16,}")
print()
check("true positives",  tp, cm["true_positives"],  tol=0.5)
check("false positives", fp, cm["false_positives"], tol=0.5)
check("false negatives", fn, cm["false_negatives"], tol=0.5)
check("true negatives",  tn, cm["true_negatives"],  tol=0.5)

print(f"\\nOf {tp + fn} real mules we flag {tp} and miss {fn} "
      f"({100 * fn / (tp + fn):.1f}% missed).")
print(f"Of {tp + fp} accounts we flag, {fp} are wrong "
      f"({100 * tp / (tp + fp):.1f}% precision).")
'''))

    c.append(md("## 5 · Why the threshold is 0.93, not 0.5"))
    c.append(code('''
ths = np.linspace(0.05, 0.99, 200)
f1s = [f1_score(y_true, (y_prob >= t).astype(int), zero_division=0) for t in ths]

fig, ax = plt.subplots(figsize=(8, 3))
ax.plot(ths, f1s, color="#3d8b00")
ax.axvline(thr, color="#c0392b", ls="--", label=f"shipped {thr:.3f}")
ax.axvline(0.5, color="#7f8c8d", ls=":", label="naive 0.5")
ax.set_xlabel("threshold"); ax.set_ylabel("F1"); ax.legend()
ax.set_title("Threshold tuning is the one hyperparameter that matters here")
plt.tight_layout(); plt.show()

print(f"F1 at shipped threshold : {f1_score(y_true, y_pred):.4f}")
print(f"F1 at 0.5               : {f1_score(y_true, (y_prob >= 0.5).astype(int)):.4f}")
print(f"published F1 @ 0.5      : {METRICS['detection']['test_f1_at_0.5']:.4f}")
'''))
    c.append(md("""
At ~3% prevalence a 0.5 cut is simply the wrong operating point. The threshold is
selected on **validation** data and then applied unchanged to test — it is not
tuned against the test set.
"""))

    c.append(md("""
## 6 · Is the graph worth anything? — baselines on the same test nodes

Every baseline below is trained on the checkpoint's own train+val indices and
scored on its own test indices. An earlier version of this comparison split the
data independently for the baselines, which meant the reported "lift" compared
two different test sets and was meaningless.
"""))
    c.append(code('''
import importlib.util
spec = importlib.util.spec_from_file_location(
    "evaluate_baselines", ROOT / "scripts" / "evaluate_baselines.py")
eb = importlib.util.module_from_spec(spec)
spec.loader.exec_module(eb)

base_df, scores_by_model, yte = eb.mule_detection_baselines(ckpt)
base_df = base_df.sort_values("f1").reset_index(drop=True)

gnn_f1 = f1_score(y_true, y_pred)
full = pd.concat([base_df[["model", "f1", "auc", "pr_auc"]],
                  pd.DataFrame([{"model": "GraphSAGE (graph)", "f1": gnn_f1,
                                 "auc": roc_auc_score(y_true, y_prob),
                                 "pr_auc": average_precision_score(y_true, y_prob)}])],
                 ignore_index=True)
display(full.round(4))

best_non_graph = base_df.f1.max()
print(f"\\nbest non-graph : {best_non_graph:.4f}")
print(f"GraphSAGE      : {gnn_f1:.4f}")
print(f"lift from graph: {gnn_f1 - best_non_graph:+.4f}")
check("lift over best non-graph", gnn_f1 - best_non_graph,
      METRICS["detection_baselines"]["lift_over_best_non_graph"])
'''))

    c.append(code('''
fig, ax = plt.subplots(figsize=(8, 3))
colors = ["#7f8c8d"] * len(base_df) + ["#3d8b00"]
ax.barh(full.model, full.f1, color=colors)
ax.set_xlabel("Test F1"); ax.set_xlim(0, 1)
ax.set_title("Same features, same split - only the graph differs")
for i, v in enumerate(full.f1):
    ax.text(v + 0.01, i, f"{v:.3f}", va="center", fontsize=8)
plt.tight_layout(); plt.show()
'''))

    c.append(md("## 7 · Against the ceiling"))
    c.append(code('''
CEILING = 0.927   # attainable F1 given irreducible label noise (OVERNIGHT_ML_AUDIT.md)
print(f"GraphSAGE F1     {gnn_f1:.4f}")
print(f"attainable       {CEILING:.4f}")
print(f"share of ceiling {100 * gnn_f1 / CEILING:.1f}%")
print(f"headroom left    {CEILING - gnn_f1:.4f} F1")

fig, ax = plt.subplots(figsize=(7, 1.6))
ax.barh(["detection"], [gnn_f1], color="#3d8b00", label="achieved")
ax.barh(["detection"], [CEILING - gnn_f1], left=[gnn_f1], color="#dfe6e9",
        label="remaining headroom")
ax.axvline(best_non_graph, color="#c0392b", ls="--", lw=1, label="best non-graph")
ax.set_xlim(0, 1); ax.legend(fontsize=8, loc="lower right")
ax.set_title("Three points of headroom exist in total")
plt.tight_layout(); plt.show()
'''))
    c.append(md("""
Six controlled experiments (`docs/gnn_experiments.csv` — halved and doubled
`pos_weight`, focal loss, three checkpoint-selection criteria) move validation F1
only between 0.8865 and 0.8971. The model is neither underfit nor mis-weighted;
the residual error is label noise and genuine behavioural overlap, which no
hyperparameter reaches.
"""))
    return c


# ───────────────────────────────────────────────────────────────────────────────
# 03 — Conditional logit ranking
# ───────────────────────────────────────────────────────────────────────────────

def nb_rank():
    c = []
    c.append(md(r"""
# 03 · Conditional logit — where the cash comes out

**Model 3 of 3, and the one the problem statement is actually about.**

This is **not** XGBoost. A gradient-boosted ranker was tried here and lost to a
plain "walk to the nearest ATM" rule, and so did a 953-way softmax over the
national ATM directory. The reason is structural.

Where a cash-out happens is a **discrete choice among alternatives**, and its
drivers compose **multiplicatively**:

$$\text{score}_i \;\propto\; \underbrace{e^{-d_i/\lambda}}_{\text{proximity}}
\times \underbrace{(1 + w\,r_i)}_{\text{surveillance risk}}
\times \underbrace{b_i}_{\text{bank affinity}}
\times \underbrace{c_i}_{\text{crew habit}}$$

A decision tree approximates a product with axis-aligned steps and does it badly.
Take logarithms and the product becomes a sum, which is exactly a conditional
logit — McFadden (1974):

$$P(\text{atm}_i \mid C) = \frac{e^{\,w \cdot \log x_i}}{\sum_{j \in C} e^{\,w \cdot \log x_j}}$$

Fitted by gradient ascent on the within-group log-likelihood of the chosen ATM.
"""))
    c.append(code(PREAMBLE))

    c.append(md("## 1 · The shipped ranker"))
    c.append(code('''
import pickle
from xgb_model import MuleXGBPredictor, OPERATING_K, CREW_HOPS

with open(MODELS / "xgb_cashout.pkl", "rb") as f:
    bundle = pickle.load(f)

ranker = bundle["classifier"]          # ConditionalLogitRanker
print("ranker       :", type(ranker).__name__)
print("weights      :", np.round(ranker.w, 4))
print("candidate K  :", bundle["candidate_k"])
print("operating K  :", OPERATING_K)
print("crew hops    :", CREW_HOPS)
print(f"\\nA {len(ranker.w)}-parameter model. The entire location forecast rests on "
      f"these {len(ranker.w)} numbers.")
'''))

    c.append(md("""
## 2 · Did it recover the real generating process?

Because the corpus is synthetic we know the true generative constants, so the
learned weights can be checked directly against them. This is the strongest
single piece of evidence that the structural choice was right rather than merely
convenient.
"""))
    c.append(code('''
TERMS = [
    ("-distance / 5",        0, 1.000,          "ATM_DISTANCE_DECAY_KM = 5.0"),
    ("log(1 + 2 * risk)",    1, 1.000,          "ATM_RISK_WEIGHT = 2.0"),
    ("same_bank",            2, np.log(2.0),    "ATM_SAME_BANK_BOOST = 2.0"),
]
rows = [{"term": t, "learned": float(ranker.w[i]), "generative_truth": g,
         "abs_error": abs(float(ranker.w[i]) - g), "source_constant": s}
        for t, i, g, s in TERMS]
display(pd.DataFrame(rows).round(4))

print("\\nRemaining weights (priors the generator does not expose a single "
      "closed-form constant for):")
for i in range(3, len(ranker.w)):
    print(f"  w[{i}] = {ranker.w[i]:+.4f}")
'''))

    c.append(md("""
## 3 · The held-out Top-K evaluation

Measured by `scripts/topk_curve.py` against the **shipped** checkpoint on the
held-out complaints of the same seed-42 `GroupShuffleSplit` the trainer used. No
retraining, no tuning; a retrieval failure counts as a miss.

That script is the source of truth and it **writes to the metrics ledger**, so
this notebook reads its published output rather than silently re-running it and
mutating project state. Flip `RECOMPUTE` if you want the full reproduction — it
re-executes the real script, and the values it produces are deterministic (only
the recorded latency and timestamp differ between runs).
"""))
    c.append(code('''
RECOMPUTE = False    # True re-runs scripts/topk_curve.py and REWRITES data/metrics.json

pub = METRICS["ranking"]

if RECOMPUTE:
    import importlib.util
    spec = importlib.util.spec_from_file_location(
        "topk_curve", ROOT / "scripts" / "topk_curve.py")
    tk = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(tk)
    result = tk.main()
    curve = pd.DataFrame(result["curve"])
else:
    curve = pd.DataFrame(pub["curve"])

display(curve[["K", "containment", "baseline", "reduction",
               "retrieval_failures", "ranking_failures"]].round(4))

at = {int(r["K"]): r for _, r in curve.iterrows()}
print()
check("top-1 containment", at[1]["containment"], pub["top1"])
check("top-3 containment", at[3]["containment"], pub["top3"])
check("top-5 containment", at[5]["containment"], pub["top5"])
check("K=5 distance baseline", at[5]["baseline"], pub["top5_baseline_distance"])
print(f"\\n  n = {pub['n_test_cashouts']} held-out cash-outs "
      f"against a {pub['n_atms']:,}-ATM directory")
'''))

    c.append(md("## 4 · The uncomfortable result, plotted honestly"))
    c.append(code('''
BAYES = {1: 0.2654, 3: 0.5744, 5: 0.7217}   # OVERNIGHT_ML_AUDIT.md, section 7

fig, ax = plt.subplots(figsize=(8, 4))
ax.plot(curve.K, curve.containment, "o-", color="#3d8b00", label="conditional logit (ours)")
ax.plot(curve.K, curve.baseline, "s--", color="#7f8c8d", label="distance-only baseline")
ax.scatter(list(BAYES), list(BAYES.values()), marker="*", s=170,
           color="#c0392b", zorder=5, label="Bayes optimum")
ax.axvline(5, color="#2f6b8a", ls=":", lw=1)
ax.annotate("operating point K=5", (5, 0.30), fontsize=8, color="#2f6b8a", rotation=90)
ax.set_xlabel("K (ATMs handed to a field team)")
ax.set_ylabel("containment - true ATM inside top-K")
ax.set_ylim(0, 1); ax.legend(fontsize=8)
ax.set_title("We do not beat distance-sorting at K=5. Neither can anything else.")
plt.tight_layout(); plt.show()

print(f"K=5   ours {pub['top5']:.4f}   distance {pub['top5_baseline_distance']:.4f}   "
      f"Bayes {BAYES[5]:.4f}")
print(f"K=1   ours {pub['top1']:.4f}   Bayes {BAYES[1]:.4f}   <- exact match")
'''))
    c.append(md("""
**Top-1 equals the Bayes bound exactly.** A paired McNemar test over the same 618
held-out cash-outs finds no significant difference against distance-sorting at
*any* K.

That is not a defect awaiting a fix — it is what an information ceiling looks
like. Of the 177 misses at K=5, **94.9% are cases where the true generative
posterior also ranked the correct ATM outside its top 5**: the offender made a
low-probability choice. Only **9 of 618 (1.5%)** are genuine model error.

The correct engineering response was to stop optimising, and to say so in
writing.
"""))

    c.append(md("""
## 5 · Retrieval never fails — so every miss is a ranking miss

Worth separating, because it tells you which knob would even matter.
"""))
    c.append(code('''
fig, ax = plt.subplots(figsize=(8, 3))
ax.bar(curve.K - 0.18, curve.retrieval_failures, width=0.36,
       color="#c0392b", label="retrieval failures (true ATM outside the 25)")
ax.bar(curve.K + 0.18, curve.ranking_failures, width=0.36,
       color="#c77b30", label="ranking failures (in the 25, outside top-K)")
ax.set_xlabel("K"); ax.set_ylabel("failures out of 618"); ax.legend(fontsize=8)
ax.set_title("Widening the candidate pool cannot help")
plt.tight_layout(); plt.show()

print(f"retrieval failure rate: {pub['retrieval_failure_rate']:.4f}")
print("The true ATM is inside the 25-candidate pool in 618 of 618 cases.")
'''))

    c.append(md("""
## 6 · What actually ships — the search zone

The deliverable is not the top-5 list. Nobody sends five separate units to five
machines. The ranked distribution is collapsed into one **search zone**, and
there the model genuinely beats every baseline at equal search cost.
"""))
    c.append(code('''
loc = METRICS["location"]
zones = pd.DataFrame([
    {"zone centre": "Mule's own location",
     "containment": loc["zone_containment_baseline_mule"], "median error km": 6.39},
    {"zone centre": "Nearest-3 ATM centroid",
     "containment": loc["zone_containment_baseline_nearest3"], "median error km": 5.68},
    {"zone centre": "MuleShield search zone",
     "containment": loc["zone_containment"], "median error km": loc["zone_median_error_km"]},
])
display(zones.round(4))

fig, ax = plt.subplots(figsize=(7.5, 2.4))
ax.barh(zones["zone centre"], zones["containment"],
        color=["#7f8c8d", "#7f8c8d", "#3d8b00"])
ax.set_xlim(0, 1); ax.set_xlabel("withdrawal contained in the zone")
for i, v in enumerate(zones["containment"]):
    ax.text(v + 0.01, i, f"{v:.1%}", va="center", fontsize=8)
plt.tight_layout(); plt.show()

print(f"search cost : 1,000 ATMs -> median {loc['zone_median_atms']:.0f} "
      f"inside a {loc['zone_median_radius_km']:.2f} km radius")
print(f"lift over best naive zone: "
      f"{loc['zone_containment'] - loc['zone_containment_baseline_nearest3']:+.4f}")
'''))
    c.append(md("""
**87.4% containment against 78.5% for the best naive zone**, at the same search
cost. This — not top-5 accuracy — is the number to lead with, because it is the
one that is both honestly ahead of its baselines and operationally meaningful.
"""))
    return c


# ───────────────────────────────────────────────────────────────────────────────
# 04 — XGBoost countdown
# ───────────────────────────────────────────────────────────────────────────────

def nb_xgb():
    c = []
    c.append(md("""
# 04 · XGBoost — the countdown

**The only job XGBoost does in this system.** It does not rank ATMs and it does
not detect mules; it estimates **minutes until withdrawal** for the top-ranked
candidate, together with a confidence band.

Gradient boosting is the right tool here for an unglamorous reason: this is a
small-n, mixed-type, tabular regression (~65k rows, 80 heterogeneous features).
A neural network needs far more data to match boosted trees on that shape and
gives up interpretability in exchange.
"""))
    c.append(code(PREAMBLE))

    c.append(md("## 1 · The model and its inputs"))
    c.append(code('''
import pickle
with open(MODELS / "xgb_cashout.pkl", "rb") as f:
    bundle = pickle.load(f)

reg    = bundle["regressor"]
reg_lo = bundle["regressor_lo"]
reg_hi = bundle["regressor_hi"]

print("regressor      :", type(reg).__name__)
print("n_estimators   :", reg.n_estimators)
print("max_depth      :", reg.max_depth)
print("learning_rate  :", reg.learning_rate)
print("quantile models:", type(reg_lo).__name__, "(q05) /", type(reg_hi).__name__, "(q95)")

from feature_builder import TABULAR_FEATURE_NAMES, EMBEDDING_DIM
print(f"\\nfeature vector: {EMBEDDING_DIM}-dim GNN embedding "
      f"+ {len(TABULAR_FEATURE_NAMES)} tabular = "
      f"{EMBEDDING_DIM + len(TABULAR_FEATURE_NAMES)}-dim")
'''))
    c.append(md("""
The quantile pair is the part that matters operationally. A single number hides
how much of the delay is genuinely unknowable; an officer being dispatched needs
"next 20-70 minutes", not "at 14:32".
"""))

    c.append(md("## 2 · Published performance"))
    c.append(code('''
loc = METRICS["location"]
rows = [
    ("Test MAE (minutes)",        loc["time_mae_minutes"]),
    ("Mean-prediction baseline",  loc["time_baseline_mae"]),
    ("R-squared",                 loc["time_r2"]),
    ("q05-q95 coverage",          loc["interval_coverage"]),
    ("Interval width (minutes)",  loc["interval_width_min"]),
    ("Median lead time (minutes)",loc["lead_time_median_min"]),
    ("Actionable rate (>=15 min)",loc["lead_actionable_rate"]),
]
display(pd.DataFrame(rows, columns=["metric", "value"]).round(4))

improve = loc["time_baseline_mae"] - loc["time_mae_minutes"]
print(f"\\nBeats the mean-guess baseline by {improve:.2f} minutes "
      f"({100 * improve / loc['time_baseline_mae']:.1f}% lower error).")
'''))

    c.append(md("## 3 · Error against the ceiling — the one model with real headroom"))
    c.append(code('''
CEILING_MAE = 9.38    # conditioned on observables (OVERNIGHT_ML_AUDIT.md, section 8)
CEILING_R2  = 0.445

achieved = loc["time_mae_minutes"]
baseline = loc["time_baseline_mae"]

fig, ax = plt.subplots(figsize=(8, 2.2))
ax.barh(["MAE (min)"], [CEILING_MAE], color="#3d8b00", label="irreducible")
ax.barh(["MAE (min)"], [achieved - CEILING_MAE], left=[CEILING_MAE],
        color="#c77b30", label="remaining headroom")
ax.barh(["MAE (min)"], [baseline - achieved], left=[achieved],
        color="#dfe6e9", label="already beaten vs baseline")
ax.axvline(achieved, color="#2c3e50", lw=1.5)
ax.text(achieved, 0.35, f" achieved {achieved:.2f}", fontsize=8, va="bottom")
ax.set_xlabel("mean absolute error (minutes)"); ax.legend(fontsize=8, loc="lower right")
plt.tight_layout(); plt.show()

print(f"achieved MAE {achieved:.2f}   ceiling {CEILING_MAE:.2f}   "
      f"headroom {achieved - CEILING_MAE:.2f} min")
print(f"achieved R2  {loc['time_r2']:.3f}   ceiling {CEILING_R2:.3f}")
'''))
    c.append(md("""
Unlike the other two components, this one is **not** at its ceiling — and the
project says so. The gap is a two-regime mixture: a crew either has a runner
already at the machine or has to travel, and which regime applies is a draw the
model cannot observe even knowing the crew's speed exactly.

Adding observed intra-chain hop timing (median gap, fastest gap, elapsed span —
all visible the moment a complaint is traced) moved MAE 12.04 -> 11.82 and
R-squared 0.155 -> 0.167. Real, but small.
"""))

    c.append(md("## 4 · Why a band and not a point estimate"))
    c.append(code('''
cov, width = loc["interval_coverage"], loc["interval_width_min"]

fig, ax = plt.subplots(figsize=(8, 2))
ax.barh(["q05-q95"], [cov], color="#3d8b00")
ax.axvline(0.90, color="#c0392b", ls="--", label="nominal 90%")
ax.set_xlim(0, 1); ax.set_xlabel("empirical coverage"); ax.legend(fontsize=8)
ax.set_title(f"Interval covers {cov:.1%} of true delays, {width:.1f} min wide")
plt.tight_layout(); plt.show()

print(f"Nominal coverage 90%, empirical {cov:.1%} - the band is somewhat")
print("narrower than advertised, which is the honest reading and is reported as such.")
'''))

    c.append(md("## 5 · What this buys operationally"))
    c.append(code('''
lead   = loc["lead_time_median_min"]
action = loc["lead_actionable_rate"]

fig, ax = plt.subplots(figsize=(7.5, 2))
ax.barh(["cases"], [action], color="#3d8b00", label=f"actionable ({action:.1%})")
ax.barh(["cases"], [1 - action], left=[action], color="#dfe6e9",
        label="too little lead time")
ax.set_xlim(0, 1); ax.legend(fontsize=8, loc="center right")
ax.set_title(f"Median {lead:.0f} minutes of warning before the predicted withdrawal")
plt.tight_layout(); plt.show()

print(f"median lead time      : {lead:.1f} min")
print(f"actionable (>=15 min) : {action:.1%}")
print(f"inference (mean/max)  : {loc['inference_mean_ms']:.2f} / "
      f"{loc['inference_max_ms']:.2f} ms")
'''))

    c.append(md("""
## Summary across all three models

| Component | Achieved | Baseline | Ceiling | Status |
|---|---|---|---|---|
| GraphSAGE detection | F1 0.8955 | 0.8423 (RF) | 0.927 | 97% of ceiling |
| Conditional logit ranking | Top-1 0.2654 | 0.2476 | 0.2654 | **at the Bayes bound** |
| Search zone (deliverable) | 87.4% | 78.5% | — | +8.9 points |
| XGBoost countdown | 11.86 min | 14.98 min | 9.38 min | headroom remains |

Two of the three components are provably done. The countdown is the honest soft
spot, and it is labelled as such here, in the audit, and on the slide deck.
"""))
    return c


def main() -> None:
    print("Building notebooks:\n")
    write("01_exploratory_data_analysis.ipynb", "dataset, chains, leakage check", nb_eda())
    write("02_graphsage_detection.ipynb",       "detection vs baselines vs ceiling", nb_gnn())
    write("03_conditional_logit_ranking.ipynb", "location, Bayes bound, search zone", nb_rank())
    write("04_xgboost_countdown.ipynb",         "timing, interval, headroom", nb_xgb())
    print(f"\nWritten to {OUT.relative_to(ROOT)}/")


if __name__ == "__main__":
    main()
